### ISSUE TITLE
Default World Generator: Exception in server tick loop

### ISSUE THREAD

**Issue by UndeadZeratul** [UndeadZeratul/ThereWillBeBlood#124]
[![YAMPST - Open source mod pack statistics tracker](http://files.yampst.net/static/banner-small.png)](https://yampst.net/)

Crash report collection powered by [YAMPST](https://yampst.net/).

### Environment data:
| Key | Value |
| --- | ----- |
| Mod pack version | 0.4.0 |
| Minecraft version | 1.7.10 |
| Side | Server side |

### Comments by pack administrator:

> Looks like someone tried starting the server with DefaultWorldGenerator, which is a client-side only mod.  I'll have to look into the possibility of this happening during "opening to LAN", and if so, I'll have to figure out something, or see if I can update DWG.

### Full crash report:

    ---- Minecraft Crash Report ----
    // I bet Cylons wouldn't have this problem.
    
    Time: 24/03/16 3:53 PM
    Description: Exception in server tick loop
    
    cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
    	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
    	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
    	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
    	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
    Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
    	at com.fireball1725.defaultworldgenerator.DefaultWorldGenerator.preInit(DefaultWorldGenerator.java:26)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    	... 5 more
    Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
    	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	... 32 more
    Caused by: java.lang.RuntimeException: Attempted to load class bdw for invalid side SERVER
    	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
    	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    	... 34 more
    
    
    A detailed walkthrough of the error, its code path and all known details is as follows:
    ---------------------------------------------------------------------------------------
    
    -- System Details --
    Details:
    	Minecraft Version: 1.7.10
    	Operating System: Linux (amd64) version 3.16.0-30-generic
    	Java Version: 1.8.0_74, Oracle Corporation
    	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    	Memory: 855661112 bytes (816 MB) / 1056309248 bytes (1007 MB) up to 1056309248 bytes (1007 MB)
    	JVM Flags: 5 total; -Xms1024M -Xmx1024M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:+AggressiveOpts
    	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 119 mods loaded, 119 mods active
    	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    	UCH	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    	UCH	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
    	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
    	UCH	InfiniBows{1.3.0 build 20} [InfiniBows] (minecraft.jar) 
    	UCH	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
    	UCH	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
    	UCH	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    	UCH	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
    	UCH	SomniaCore{1.3.1.55} [SomniaCore] (minecraft.jar) 
    	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    	UCH	tnt_utilities_core{1.1-beta} [TNTUtils Core] (minecraft.jar) 
    	UCH	debug{1.0} [debug] (denseores-1.6.2.jar) 
    	UCH	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.2.jar) 
    	UCH	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
    	UCH	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
    	UCH	DirectionHUD{1.24} [DirectionHUD] ([1.7.10]DirectionHUD-client-1.24.jar) 
    	UCH	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) 
    	UCH	AgriCraft{1.7.10-1.4.6-hotfix} [AgriCraft] (AgriCraft-1.7.10-1.4.6-hotfix.jar) 
    	UCH	airoverhaul{1.7.10_1.0} [Air Overhaul] (airoverhaul-1.7.10_1.0.jar) 
    	UCH	antiqueatlas{1.7.10-4.2.10} [Antique Atlas] (antiqueatlas-1.7.10-4.2.10.jar) 
    	UCH	aobdbb{1.0.6} [Another One Bites The Dust: Berry Bushes] (AOBDBB-1.0.6.jar) 
    	UCH	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
    	UCH	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
    	UCH	AromaBackup{0.0.0.6} [AromaBackup] (AromaBackup-1.7.10-0.0.0.6.jar) 
    	UCH	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.7.10-0.0.0.6.jar) 
    	UCH	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
    	UCH	asielib{0.4.5} [asielib] (AsieLib-1.7.10-0.4.5.jar) 
    	UCH	ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.10-0.12.0.jar) 
    	UCH	excore{1.3.2} [EXCore] (Excore-1.3.2-1.7.10.jar) 
    	UCH	avoidexplodingcreepers{2.0} [Avoid Exploding Creepers] (AvoidExplodingCreepers-1.7.10-LATEST.jar) 
    	UCH	BetterFoliage{2.0.2} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.2.jar) 
    	UCH	betterstorage{0.13.1.127} [BetterStorage] (BetterStorage-1.7.10-0.13.1.127.jar) 
    	UCH	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
    	UCH	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
    	UCH	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1387-universal.jar) 
    	UCH	BlockProperties{0.1.4} [Block Properties] (BlockProperties-1.7.10-0.1.4.jar) 
    	UCH	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
    	UCH	cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
    	UCH	cookingbook{1.0.134} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.134.jar) 
    	UCH	BuildMod{v1.0} [Build Mod] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCH	CoroPets{v1.0} [CoroPets] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCH	CoroAI{v1.0} [CoroAI] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCH	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCH	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCH	creativecore{1.0} [CreativeCore] (CreativeCore v1.1.2 mc1.7.10.jar) 
    	UCH	DamageIndicatorsMod{3.2.3} [Damage Indicators] (DamageIndicatorsMod-3.2.3.jar) 
    	UCH	menagerie{1.0} [menagerie] (dark_menagerie-1.7.10-beta-3.1a.jar) 
    	UCH	DeadlyWorld{1.0.2} [Deadly World] (DeadlyWorld-1.7.10-1.0.2.jar) 
    	UCE	defaultworldgenerator{0.1-b13} [Default World Generator] (DefaultWorldGenerator-1.7.10-0.1-b13-universal.jar) 
    	UCH	dimdoors{2.2.5-test9} [Dimensional Doors] (DimensionalDoors-2.2.5-test9.jar) 
    	UCH	dldungeonsjdg{1.8.5} [Doomlike Dungeons] (DoomlikeDungeons-1.8.5-MC1.7.10.jar) 
    	UCH	enviromine{1.3.124} [EnviroMine] (EnviroMine-1.3.124.jar) 
    	UCH	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
    	UCH	Steamcraft{0.28.12} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.28.12.jar) 
    	UCH	hammerz{0.1.7.36} [Hammerz] (Hammerz-1.7.10-0.1.7.36.jar) 
    	UCH	HardcoreEnderExpansion{1.8.5} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.5.jar) 
    	UCH	IguanaTweaks{2B} [Iguana Tweaks] (IguanaTweaks-1.7.10-2B-snapshot-3.jar) 
    	UCH	InfernalMobs{1.6.1} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
    	UCH	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
    	UCH	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
    	UCH	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
    	UCH	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCH	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCH	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCH	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCH	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCH	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCH	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCH	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCH	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCH	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCH	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCH	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCH	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCH	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
    	UCH	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
    	UCH	TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.build991.jar) 
    	UCH	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
    	UCH	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar) 
    	UCH	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
    	UCH	MobProperties{0.4.3} [Mob Properties] (MobProperties-1.7.10-0.4.3.jar) 
    	UCH	modpackTweaks{1.2.0} [ModpackTweaks] (ModpackTweaks-MC1.7.10-1.2.0-21.jar) 
    	UCH	modtweaker2{0.9.5} [Mod Tweaker 2] (ModTweaker2-0.9.5.jar) 
    	UCH	NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) 
    	UCH	neiintegration{1.1.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.1.jar) 
    	UCH	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
    	UCH	nincraftlib{1.7.10-0.1.1+24} [Nincraft Lib] (NincraftLib-1.7.10-0.1.1+24.jar) 
    	UCH	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
    	UCH	temperateplants{1.7.2b} [Pam's Temperate Plants] (Pam's Temperate Plants 1.7.2b.zip) 
    	UCH	PneumaticCraft{1.12.4-147} [PneumaticCraft] (PneumaticCraft-1.7.10-1.12.4-147-universal.jar) 
    	UCH	PoorOres{1.7.10-1.4.8} [PoorOres] (PoorOres-1.7.10-1.4.8.jar) 
    	UCH	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) 
    	UCH	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
    	UCH	RPGAdvMod{1.0.0} [RPGAdvMod] (RPGAdvMod-1.0.0_1.7.10.jar) 
    	UCH	Somnia{-au} [Somnia] (Somnia-1.4.8.55.jar) 
    	UCH	SpecialAI{1.1.1} [Special AI] (SpecialAI-1.7.10-1.1.1.jar) 
    	UCH	SpecialMobs{3.2.1} [Special Mobs] (SpecialMobs-1.7.10-3.2.1.jar) 
    	UCH	SpiceOfLife{1.3.0} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.0.jar) 
    	UCH	Stackie{1.6.0.36} [Stackie] (Stackie-1.7.10-1.6.0.36-universal.jar) 
    	UCH	tnt_utilities{1.1-beta} [TNTUtils] (tnt_utilities-1.1-beta.jar) 
    	UCH	TML{4.0.1} [TooMuchLoot] (TooMuchLoot-1.7.10-4.0.1.B0.jar) 
    	UCH	TSteelworks{1.7.10-1.1.1} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.1-17.jar) 
    	UCH	twbbtweaks{1.7.10-0.0.1+3} [TWBB Tweaks] (TWBBTweaks-1.7.10-0.0.1+3.jar) 
    	UCH	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
    	UCH	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
    	UCH	weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) 
    	UCH	yampst{1.3.5} [YAMPST] (Yampst-There Will Be Blood-0.4.0.jar) 
    	UCH	YeOldeTanks{1.2.0} [Ye Olde Tanks] (YeOldeTanks-1.7.10-1.4.5.jar) 
    	UCH	ZAMod{v1.9.5} [Zombie Awareness] (ZombieAwareness-1.9.6.jar) 
    	UCH	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    	UCH	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    	UCH	aobd{2.9.0} [Another One Bites The Dust] (AOBD-2.9.0.jar) 
    	UCH	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
    	UCH	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
    	UCH	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
    	UCH	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    	CoFHCore: -[1.7.10]3.0.3-303
    	Mantle Environment: Environment healthy.
    	ThermalFoundation: -[1.7.10]1.2.0-102
    	TConstruct Environment: Environment healthy.
    	NetherOres: -[1.7.10]2.3.0-12
    	Profiler Position: N/A (disabled)
    	Is Modded: Definitely; Server brand changed to 'fml,forge'
    	Type: Dedicated Server (map_server.txt)

**Comment by UndeadZeratul** [comment]
I can't seem to recreate this issue, but that doesn't mean it's been fixed.  I'll push this to v1.1 and if I can confirm it being fixed, I'll close it then.

**Comment by UndeadZeratul** [comment]
Yeah, upon looking at the crash report more closely, it seems this was a dedicated server that crashed because it had a clientside mod included.  Since I have a server zip available, I'm going to close this as it seems to have been just user error.
