### ISSUE TITLE
Crash: Exception in server tick loop

### ISSUE THREAD

**Issue by UndeadZeratul** [UndeadZeratul/ThereWillBeBlood#125]
[![YAMPST - Open source mod pack statistics tracker](http://files.yampst.net/static/banner-small.png)](https://yampst.net/)

Crash report collection powered by [YAMPST](https://yampst.net/).

### Environment data:
| Key | Value |
| --- | ----- |
| Mod pack version | 0.4.0 |
| Minecraft version | 1.7.10 |
| Side | Server side |

### Comments by pack administrator:

> Looks like DamageIndicatorsMod caused a problem by trying to run client-side code on a supposed server.  Since DamageIndicatorsMod is nor longer included, this is probably a false alarm, but it doesn't hurt to double check things before release.

### Full crash report:

    ---- Minecraft Crash Report ----
    // You're mean.
    
    Time: 24/03/16 4:03 PM
    Description: Exception in server tick loop
    
    cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
    	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
    	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
    Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
    	at DamageIndicatorsMod.server.DIProxy.register(DIProxy.java:11)
    	at DamageIndicatorsMod.DIMod.load(DIMod.java:64)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    	... 5 more
    Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
    	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	... 33 more
    Caused by: java.lang.RuntimeException: Attempted to load class bjf for invalid side SERVER
    	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
    	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    	... 35 more
    
    
    A detailed walkthrough of the error, its code path and all known details is as follows:
    ---------------------------------------------------------------------------------------
    
    -- System Details --
    Details:
    	Minecraft Version: 1.7.10
    	Operating System: Linux (amd64) version 3.16.0-30-generic
    	Java Version: 1.8.0_74, Oracle Corporation
    	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    	Memory: 784490664 bytes (748 MB) / 1056309248 bytes (1007 MB) up to 1056309248 bytes (1007 MB)
    	JVM Flags: 5 total; -Xms1024M -Xmx1024M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:+AggressiveOpts
    	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 118 mods loaded, 118 mods active
    	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    	UCHI	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    	UCHI	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
    	UCHI	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
    	UCHI	InfiniBows{1.3.0 build 20} [InfiniBows] (minecraft.jar) 
    	UCHI	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
    	UCHI	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
    	UCHI	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    	UCHI	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
    	UCHI	SomniaCore{1.3.1.55} [SomniaCore] (minecraft.jar) 
    	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    	UCHI	tnt_utilities_core{1.1-beta} [TNTUtils Core] (minecraft.jar) 
    	UCHI	debug{1.0} [debug] (denseores-1.6.2.jar) 
    	UCHI	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.2.jar) 
    	UCHI	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
    	UCHI	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
    	UCHI	DirectionHUD{1.24} [DirectionHUD] ([1.7.10]DirectionHUD-client-1.24.jar) 
    	UCHI	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) 
    	UCHI	AgriCraft{1.7.10-1.4.6-hotfix} [AgriCraft] (AgriCraft-1.7.10-1.4.6-hotfix.jar) 
    	UCHI	airoverhaul{1.7.10_1.0} [Air Overhaul] (airoverhaul-1.7.10_1.0.jar) 
    	UCHI	antiqueatlas{1.7.10-4.2.10} [Antique Atlas] (antiqueatlas-1.7.10-4.2.10.jar) 
    	UCHI	aobdbb{1.0.6} [Another One Bites The Dust: Berry Bushes] (AOBDBB-1.0.6.jar) 
    	UCHI	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
    	UCHI	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
    	UCHI	AromaBackup{0.0.0.6} [AromaBackup] (AromaBackup-1.7.10-0.0.0.6.jar) 
    	UCHI	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.7.10-0.0.0.6.jar) 
    	UCHI	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
    	UCHI	asielib{0.4.5} [asielib] (AsieLib-1.7.10-0.4.5.jar) 
    	UCHI	ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.10-0.12.0.jar) 
    	UCHI	excore{1.3.2} [EXCore] (Excore-1.3.2-1.7.10.jar) 
    	UCHI	avoidexplodingcreepers{2.0} [Avoid Exploding Creepers] (AvoidExplodingCreepers-1.7.10-LATEST.jar) 
    	UCHI	BetterFoliage{2.0.2} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.2.jar) 
    	UCHI	betterstorage{0.13.1.127} [BetterStorage] (BetterStorage-1.7.10-0.13.1.127.jar) 
    	UCHI	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
    	UCHI	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
    	UCHI	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1387-universal.jar) 
    	UCHI	BlockProperties{0.1.4} [Block Properties] (BlockProperties-1.7.10-0.1.4.jar) 
    	UCHI	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
    	UCHI	cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
    	UCHI	cookingbook{1.0.134} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.134.jar) 
    	UCHI	BuildMod{v1.0} [Build Mod] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCHI	CoroPets{v1.0} [CoroPets] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCHI	CoroAI{v1.0} [CoroAI] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCHI	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCHI	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCHI	creativecore{1.0} [CreativeCore] (CreativeCore v1.1.2 mc1.7.10.jar) 
    	UCHE	DamageIndicatorsMod{3.2.3} [Damage Indicators] (DamageIndicatorsMod-3.2.3.jar) 
    	UCHI	menagerie{1.0} [menagerie] (dark_menagerie-1.7.10-beta-3.1a.jar) 
    	UCHI	DeadlyWorld{1.0.2} [Deadly World] (DeadlyWorld-1.7.10-1.0.2.jar) 
    	UCHI	dimdoors{2.2.5-test9} [Dimensional Doors] (DimensionalDoors-2.2.5-test9.jar) 
    	UCHI	dldungeonsjdg{1.8.5} [Doomlike Dungeons] (DoomlikeDungeons-1.8.5-MC1.7.10.jar) 
    	UCHI	enviromine{1.3.124} [EnviroMine] (EnviroMine-1.3.124.jar) 
    	UCHI	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
    	UCHI	Steamcraft{0.28.12} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.28.12.jar) 
    	UCHI	hammerz{0.1.7.36} [Hammerz] (Hammerz-1.7.10-0.1.7.36.jar) 
    	UCHI	HardcoreEnderExpansion{1.8.5} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.5.jar) 
    	UCHI	IguanaTweaks{2B} [Iguana Tweaks] (IguanaTweaks-1.7.10-2B-snapshot-3.jar) 
    	UCHI	InfernalMobs{1.6.1} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
    	UCHI	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
    	UCHI	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
    	UCHI	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
    	UCHI	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHI	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHI	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHI	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHI	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHI	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHI	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHI	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHI	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHI	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHI	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHI	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHI	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHI	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
    	UCHI	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    	UCHI	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
    	UCHI	TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.build991.jar) 
    	UCHI	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
    	UCHI	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar) 
    	UCHI	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
    	UCHI	MobProperties{0.4.3} [Mob Properties] (MobProperties-1.7.10-0.4.3.jar) 
    	UCHI	modpackTweaks{1.2.0} [ModpackTweaks] (ModpackTweaks-MC1.7.10-1.2.0-21.jar) 
    	UCHI	modtweaker2{0.9.5} [Mod Tweaker 2] (ModTweaker2-0.9.5.jar) 
    	UCHI	NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) 
    	UCHI	neiintegration{1.1.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.1.jar) 
    	UCHI	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
    	UCHI	nincraftlib{1.7.10-0.1.1+24} [Nincraft Lib] (NincraftLib-1.7.10-0.1.1+24.jar) 
    	UCHI	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
    	UCHI	temperateplants{1.7.2b} [Pam's Temperate Plants] (Pam's Temperate Plants 1.7.2b.zip) 
    	UCHI	PneumaticCraft{1.12.4-147} [PneumaticCraft] (PneumaticCraft-1.7.10-1.12.4-147-universal.jar) 
    	UCHI	PoorOres{1.7.10-1.4.8} [PoorOres] (PoorOres-1.7.10-1.4.8.jar) 
    	UCHI	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) 
    	UCHI	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
    	UCHI	RPGAdvMod{1.0.0} [RPGAdvMod] (RPGAdvMod-1.0.0_1.7.10.jar) 
    	UCHI	Somnia{-au} [Somnia] (Somnia-1.4.8.55.jar) 
    	UCHI	SpecialAI{1.1.1} [Special AI] (SpecialAI-1.7.10-1.1.1.jar) 
    	UCHI	SpecialMobs{3.2.1} [Special Mobs] (SpecialMobs-1.7.10-3.2.1.jar) 
    	UCHI	SpiceOfLife{1.3.0} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.0.jar) 
    	UCHI	Stackie{1.6.0.36} [Stackie] (Stackie-1.7.10-1.6.0.36-universal.jar) 
    	UCHI	tnt_utilities{1.1-beta} [TNTUtils] (tnt_utilities-1.1-beta.jar) 
    	UCHI	TML{4.0.1} [TooMuchLoot] (TooMuchLoot-1.7.10-4.0.1.B0.jar) 
    	UCHI	TSteelworks{1.7.10-1.1.1} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.1-17.jar) 
    	UCHI	twbbtweaks{1.7.10-0.0.1+3} [TWBB Tweaks] (TWBBTweaks-1.7.10-0.0.1+3.jar) 
    	UCHI	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
    	UCHI	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
    	UCHI	weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) 
    	UCHI	yampst{1.3.5} [YAMPST] (Yampst-There Will Be Blood-0.4.0.jar) 
    	UCHI	YeOldeTanks{1.2.0} [Ye Olde Tanks] (YeOldeTanks-1.7.10-1.4.5.jar) 
    	UCHI	ZAMod{v1.9.5} [Zombie Awareness] (ZombieAwareness-1.9.6.jar) 
    	UCHI	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    	UCHI	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    	UCHI	aobd{2.9.0} [Another One Bites The Dust] (AOBD-2.9.0.jar) 
    	UCHI	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
    	UCHI	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
    	UCHI	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
    	UCHI	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    	CoFHCore: -[1.7.10]3.0.3-303
    	Mantle Environment: Environment healthy.
    	ThermalFoundation: -[1.7.10]1.2.0-102
    	TConstruct Environment: Environment healthy.
    	NetherOres: -[1.7.10]2.3.0-12
    	Profiler Position: N/A (disabled)
    	Is Modded: Definitely; Server brand changed to 'fml,forge'
    	Type: Dedicated Server (map_server.txt)

**Comment by UndeadZeratul** [comment]
I'm Marking this as a Won't Fix, because Damage Indicators is what's causing the issue, which is no longer included.
