### ISSUE TITLE
Creeper Awareness: Concurrent Modification Exception

### ISSUE THREAD

**Issue by UndeadZeratul** [UndeadZeratul/ThereWillBeBlood#128]
[![YAMPST - Open source mod pack statistics tracker](http://files.yampst.net/static/banner-small.png)](https://yampst.net/)

Crash report collection powered by [YAMPST](https://yampst.net/).

### Environment data:
| Key | Value |
| --- | ----- |
| Mod pack version | 0.4.0 |
| Minecraft version | 1.7.10 |
| Side | Client side |

### Comments by pack administrator:

> Looks like Creeper Awareness is causing a Concurrent Modification Exception in their Explosion Source Manager;  I'll see if Elix_x can fix.

### Full crash report:

    ---- Minecraft Crash Report ----
    // Quite honestly, I wouldn't worry myself about that.
    
    Time: 3/31/16 2:08 AM
    Description: Exception in server tick loop
    
    java.util.ConcurrentModificationException
    	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    	at java.util.ArrayList$Itr.next(Unknown Source)
    	at code.elix_x.mods.avoidexplodingcreepers.api.ExplosionSrcManager.tick(ExplosionSrcManager.java:128)
    	at code.elix_x.mods.avoidexplodingcreepers.api.ExplosionSrcManager.access$000(ExplosionSrcManager.java:41)
    	at code.elix_x.mods.avoidexplodingcreepers.api.ExplosionSrcManager$TickEvent.onTickWorld(ExplosionSrcManager.java:89)
    	at cpw.mods.fml.common.eventhandler.ASMEventHandler_512_TickEvent_onTickWorld_WorldTickEvent.invoke(.dynamic)
    	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
    	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
    	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
    
    
    A detailed walkthrough of the error, its code path and all known details is as follows:
    ---------------------------------------------------------------------------------------
    
    -- System Details --
    Details:
    	Minecraft Version: 1.7.10
    	Operating System: Windows 8.1 (amd64) version 6.3
    	Java Version: 1.8.0_73, Oracle Corporation
    	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    	Memory: 629475976 bytes (600 MB) / 1129840640 bytes (1077 MB) up to 1908932608 bytes (1820 MB)
    	JVM Flags: 3 total; -Xms256M -Xmx2048M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
    	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    	IntCache: cache: 0, tcache: 53755, allocated: 0, tallocated: 4608
    	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 133 mods loaded, 133 mods active
    	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    	UCHIJAAAA	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
    	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
    	UCHIJAAAA	InfiniBows{1.3.0 build 20} [InfiniBows] (minecraft.jar) 
    	UCHIJAAAA	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
    	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
    	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    	UCHIJAAAA	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
    	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    	UCHIJAAAA	tnt_utilities_core{1.1-beta} [TNTUtils Core] (minecraft.jar) 
    	UCHIJAAAA	debug{1.0} [debug] (denseores-1.6.2.jar) 
    	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.2.jar) 
    	UCHIJAAAA	AgriCraft{1.7.10-1.4.6-hotfix} [AgriCraft] (AgriCraft-1.7.10-1.4.6-hotfix.jar) 
    	UCHIJAAAA	airoverhaul{1.7.10_1.0} [Air Overhaul] (airoverhaul-1.7.10_1.0.jar) 
    	UCHIJAAAA	antiqueatlas{1.7.10-4.2.10} [Antique Atlas] (antiqueatlas-1.7.10-4.2.10.jar) 
    	UCHIJAAAA	aobdbb{1.0.6} [Another One Bites The Dust: Berry Bushes] (AOBDBB-1.0.6.jar) 
    	UCHIJAAAA	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
    	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
    	UCHIJAAAA	ArmorStatusHUD{1.28} [ArmorStatusHUD] (ArmorStatusHUD-client-1.28.jar) 
    	UCHIJAAAA	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
    	UCHIJAAAA	AromaBackup{0.0.0.6} [AromaBackup] (AromaBackup-1.7.10-0.0.0.6.jar) 
    	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.7.10-0.0.0.6.jar) 
    	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
    	UCHIJAAAA	asielib{0.4.5} [asielib] (AsieLib-1.7.10-0.4.5.jar) 
    	UCHIJAAAA	ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.10-0.12.0.jar) 
    	UCHIJAAAA	excore{1.3.2} [EXCore] (Excore-1.3.2-1.7.10.jar) 
    	UCHIJAAAA	avoidexplodingcreepers{2.0} [Avoid Exploding Creepers] (AvoidExplodingCreepers-1.7.10-LATEST.jar) 
    	UCHIJAAAA	BetterFoliage{2.0.2} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.2.jar) 
    	UCHIJAAAA	betterstorage{0.13.1.127} [BetterStorage] (BetterStorage-1.7.10-0.13.1.127.jar) 
    	UCHIJAAAA	BetterTitleScreen{1.7.10-1.1} [Better Title Screen] (BetterTitleScreen-1.7.10-1.1.jar) 
    	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
    	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
    	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
    	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1387-universal.jar) 
    	UCHIJAAAA	BlockProperties{0.1.4} [Block Properties] (BlockProperties-1.7.10-0.1.4.jar) 
    	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
    	UCHIJAAAA	cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
    	UCHIJAAAA	cookingbook{1.0.134} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.134.jar) 
    	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.2 for MC v1.7.10.jar) 
    	UCHIJAAAA	creativecore{1.0} [CreativeCore] (CreativeCore v1.1.2 mc1.7.10.jar) 
    	UCHIJAAAA	DamageIndicatorsMod{3.2.3} [Damage Indicators] (DamageIndicatorsMod-3.2.3.jar) 
    	UCHIJAAAA	menagerie{1.0} [menagerie] (dark_menagerie-1.7.10-beta-3.1a.jar) 
    	UCHIJAAAA	DeadlyWorld{1.0.2} [Deadly World] (DeadlyWorld-1.7.10-1.0.2.jar) 
    	UCHIJAAAA	defaultworldgenerator{0.1-b13} [Default World Generator] (DefaultWorldGenerator-1.7.10-0.1-b13-universal.jar) 
    	UCHIJAAAA	dimdoors{2.2.5-test9} [Dimensional Doors] (DimensionalDoors-2.2.5-test9.jar) 
    	UCHIJAAAA	DirectionHUD{1.24} [DirectionHUD] (DirectionHUD-client-1.24.jar) 
    	UCHIJAAAA	dldungeonsjdg{1.8.5} [Doomlike Dungeons] (DoomlikeDungeons-1.8.5-MC1.7.10.jar) 
    	UCHIJAAAA	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAA	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAA	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAA	enviromine{1.3.124} [EnviroMine] (EnviroMine-1.3.124.jar) 
    	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
    	UCHIJAAAA	Steamcraft{0.28.12} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.28.12.jar) 
    	UCHIJAAAA	hammerz{0.1.7.36} [Hammerz] (Hammerz-1.7.10-0.1.7.36.jar) 
    	UCHIJAAAA	HardcoreEnderExpansion{1.8.5} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.5.jar) 
    	UCHIJAAAA	IguanaTweaks{2B} [Iguana Tweaks] (IguanaTweaks-1.7.10-2B-snapshot-3.jar) 
    	UCHIJAAAA	InfernalMobs{1.6.1} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
    	UCHIJAAAA	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
    	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
    	UCHIJAAAA	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
    	UCHIJAAAA	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAA	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAA	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAA	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAA	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAA	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAA	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAA	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAA	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAA	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAA	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAA	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAA	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAA	RadixCore{2.1.1} [RadixCore] (RadixCore-1.7.10-2.1.1-universal (1).jar) 
    	UCHIJAAAA	MCA{1.7.10-5.1.2} [Minecraft Comes Alive] (MCA-1.7.10-5.1.2-universal.jar) 
    	UCHIJAAAA	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
    	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
    	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.build991.jar) 
    	UCHIJAAAA	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
    	UCHIJAAAA	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar) 
    	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
    	UCHIJAAAA	MobProperties{0.4.3} [Mob Properties] (MobProperties-1.7.10-0.4.3.jar) 
    	UCHIJAAAA	modpackTweaks{1.2.0} [ModpackTweaks] (ModpackTweaks-MC1.7.10-1.2.0-21.jar) 
    	UCHIJAAAA	modtweaker2{0.9.5} [Mod Tweaker 2] (ModTweaker2-0.9.5.jar) 
    	UCHIJAAAA	NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) 
    	UCHIJAAAA	neiintegration{1.1.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.1.jar) 
    	UCHIJAAAA	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
    	UCHIJAAAA	nincraftlib{1.7.10-0.1.1+24} [Nincraft Lib] (NincraftLib-1.7.10-0.1.1+24.jar) 
    	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
    	UCHIJAAAA	temperateplants{1.7.2b} [Pam's Temperate Plants] (Pam's Temperate Plants 1.7.2b.zip) 
    	UCHIJAAAA	PneumaticCraft{1.12.4-147} [PneumaticCraft] (PneumaticCraft-1.7.10-1.12.4-147-universal.jar) 
    	UCHIJAAAA	PoorOres{1.7.10-1.4.8} [PoorOres] (PoorOres-1.7.10-1.4.8.jar) 
    	UCHIJAAAA	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) 
    	UCHIJAAAA	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
    	UCHIJAAAA	RPGAdvMod{1.0.0} [RPGAdvMod] (RPGAdvMod-1.0.0_1.7.10.jar) 
    	UCHIJAAAA	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
    	UCHIJAAAA	SpecialAI{1.1.1} [Special AI] (SpecialAI-1.7.10-1.1.1.jar) 
    	UCHIJAAAA	SpecialMobs{3.2.1} [Special Mobs] (SpecialMobs-1.7.10-3.2.1.jar) 
    	UCHIJAAAA	SpiceOfLife{1.3.0} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.0.jar) 
    	UCHIJAAAA	Stackie{1.6.0.36} [Stackie] (Stackie-1.7.10-1.6.0.36-universal.jar) 
    	UCHIJAAAA	StatusEffectHUD{1.27} [StatusEffectHUD] (StatusEffectHUD-client-1.27.jar) 
    	UCHIJAAAA	tnt_utilities{1.1-beta} [TNTUtils] (tnt_utilities-1.1-beta.jar) 
    	UCHIJAAAA	TML{4.0.1} [TooMuchLoot] (TooMuchLoot-1.7.10-4.0.1.B0.jar) 
    	UCHIJAAAA	TSteelworks{1.7.10-1.1.1} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.1-17.jar) 
    	UCHIJAAAA	twbbtweaks{1.7.10-0.0.1+3} [TWBB Tweaks] (TWBBTweaks-1.7.10-0.0.1+3.jar) 
    	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
    	UCHIJAAAA	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
    	UCHIJAAAA	weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) 
    	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
    	UCHIJAAAA	yampst{1.3.5} [YAMPST] (Yampst-There Will Be Blood-0.4.0.jar) 
    	UCHIJAAAA	YeOldeTanks{1.2.0} [Ye Olde Tanks] (YeOldeTanks-1.7.10-1.4.5.jar) 
    	UCHIJAAAA	ZAMod{v1.9.5} [Zombie Awareness] (ZombieAwareness-1.9.6.jar) 
    	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    	UCHIJAAAA	aobd{2.9.0} [Another One Bites The Dust] (AOBD-2.9.0.jar) 
    	UCHIJAAAA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
    	UCHIJAAAA	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
    	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
    	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    	CoFHCore: -[1.7.10]3.0.3-303
    	Mantle Environment: Environment healthy.
    	ThermalFoundation: -[1.7.10]1.2.0-102
    	TConstruct Environment: Environment healthy.
    	NetherOres: -[1.7.10]2.3.0-12
    	Profiler Position: N/A (disabled)
    	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    	Player Count: 1 / 8; [EntityPlayerMP['Scydra'/3416, l='New World', x=512.09, y=74.00, z=-1130.82]]
    	Type: Integrated Server (map_client.txt)
    	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by UndeadZeratul** [comment]
Looks like Elix_X fixed it with v2.0.1

http://minecraft.curseforge.com/projects/creeper-awareness/files/2300715

All I should have to do is update, so this is back on the v1.0 release.
