### ISSUE TITLE
Creeper Awareness: Concurrent Modification Exception in ExplosionSrcManager

### ISSUE THREAD

**Issue by UndeadZeratul** [UndeadZeratul/ThereWillBeBlood#145]
[![YAMPST - Open source mod pack statistics tracker](http://files.yampst.net/static/banner-small.png)](https://yampst.net/)

Crash report collection powered by [YAMPST](https://yampst.net/).

### Environment data:
| Key | Value |
| --- | ----- |
| Mod pack version | 1.0.0-FTB-Curse |
| Minecraft version | 1.7.10 |
| Side | Client side |

### Comments by pack administrator:

> Looks like it's still #128 creeping back up, which honestly makes no sense, that should've been taken care of...

### Full crash report:

    ---- Minecraft Crash Report ----
    // Why is it breaking :(
    
    Time: 6/6/16 10:36 AM
    Description: Exception in server tick loop
    
    java.util.ConcurrentModificationException
    	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    	at java.util.ArrayList$Itr.next(Unknown Source)
    	at code.elix_x.mods.creeperawareness.api.ExplosionSrcManager.tick(ExplosionSrcManager.java:131)
    	at code.elix_x.mods.creeperawareness.api.ExplosionSrcManager.access$000(ExplosionSrcManager.java:42)
    	at code.elix_x.mods.creeperawareness.api.ExplosionSrcManager$TickEvent.onTickWorld(ExplosionSrcManager.java:86)
    	at cpw.mods.fml.common.eventhandler.ASMEventHandler_538_TickEvent_onTickWorld_WorldTickEvent.invoke(.dynamic)
    	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
    	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
    	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
    
    
    A detailed walkthrough of the error, its code path and all known details is as follows:
    ---------------------------------------------------------------------------------------
    
    -- System Details --
    Details:
    	Minecraft Version: 1.7.10
    	Operating System: Windows 10 (amd64) version 10.0
    	Java Version: 1.8.0_91, Oracle Corporation
    	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    	Memory: 617817224 bytes (589 MB) / 2440036352 bytes (2327 MB) up to 2440036352 bytes (2327 MB)
    	JVM Flags: 3 total; -Xms256M -Xmx2560M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
    	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    	IntCache: cache: 46, tcache: 1, allocated: 53, tallocated: 60
    	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 135 mods loaded, 135 mods active
    	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    	UCHIJAAAAAAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    	UCHIJAAAAAAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
    	UCHIJAAAAAAAAAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
    	UCHIJAAAAAAAAAAAAAA	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
    	UCHIJAAAAAAAAAAAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
    	UCHIJAAAAAAAAAAAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
    	UCHIJAAAAAAAAAAAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    	UCHIJAAAAAAAAAAAAAA	SomniaCore{1.3.1.55} [SomniaCore] (minecraft.jar) 
    	UCHIJAAAAAAAAAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    	UCHIJAAAAAAAAAAAAAA	tnt_utilities_core{1.1.3} [TNTUtils Core] (minecraft.jar) 
    	UCHIJAAAAAAAAAAAAAA	debug{1.0} [debug] (denseores-1.6.2.jar) 
    	UCHIJAAAAAAAAAAAAAA	CustomOreGen{1.2.24} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.24.jar) 
    	UCHIJAAAAAAAAAAAAAA	HardLib{13.21.0a} [HardLib] (1.7.10-HardLib-13.21.0a.jar) 
    	UCHIJAAAAAAAAAAAAAA	HarderWildlife{13.21.0a} [Harder Wildlife] (1.7.10-HarderWildlife-13.21.0a.jar) 
    	UCHIJAAAAAAAAAAAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
    	UCHIJAAAAAAAAAAAAAA	OreFlowers{1.0.0} [Ore Flowers] (1.7.10-OreFlowers-3.0.1c.jar) 
    	UCHIJAAAAAAAAAAAAAA	creativecore{1.3.14} [CreativeCore] (1293.CreativeCore v1.3.23 mc1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
    	UCHIJAAAAAAAAAAAAAA	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
    	UCHIJAAAAAAAAAAAAAA	DirectionHUD{1.24} [DirectionHUD] ([1.7.10]DirectionHUD-client-1.24.jar) 
    	UCHIJAAAAAAAAAAAAAA	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar) 
    	UCHIJAAAAAAAAAAAAAA	antiqueatlas{1.7.10-4.2.10} [Antique Atlas] (antiqueatlas-1.7.10-4.2.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	aobdbb{1.0.6} [Another One Bites The Dust: Berry Bushes] (AOBDBB-1.0.6.jar) 
    	UCHIJAAAAAAAAAAAAAA	AppleCore{1.3.0} [AppleCore] (AppleCore-mc1.7.10-1.3.0.jar) 
    	UCHIJAAAAAAAAAAAAAA	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
    	UCHIJAAAAAAAAAAAAAA	AromaBackup{0.1.0.0} [AromaBackup] (AromaBackup-1.7.10-0.1.0.0.jar) 
    	UCHIJAAAAAAAAAAAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.7.10-0.1.0.0.jar) 
    	UCHIJAAAAAAAAAAAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
    	UCHIJAAAAAAAAAAAAAA	asielib{0.4.5} [asielib] (AsieLib-1.7.10-0.4.5.jar) 
    	UCHIJAAAAAAAAAAAAAA	betterbeginnings{0.9.5-R7} [BetterBeginnings] (betterbeginnings-MC1.7.10-b0.9.5-R7.jar) 
    	UCHIJAAAAAAAAAAAAAA	BetterFoliage{2.0.7} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.7.jar) 
    	UCHIJAAAAAAAAAAAAAA	betterstorage{0.13.1.127} [BetterStorage] (BetterStorage-1.7.10-0.13.1.127.jar) 
    	UCHIJAAAAAAAAAAAAAA	BetterTitleScreen{1.7.10-1.1} [Better Title Screen] (BetterTitleScreen-1.7.10-1.1.jar) 
    	UCHIJAAAAAAAAAAAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
    	UCHIJAAAAAAAAAAAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
    	UCHIJAAAAAAAAAAAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
    	UCHIJAAAAAAAAAAAAAA	BlockProperties{0.1.4} [Block Properties] (BlockProperties-1.7.10-0.1.4.jar) 
    	UCHIJAAAAAAAAAAAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
    	UCHIJAAAAAAAAAAAAAA	climatecontrol{0.4} [Climate Control] (ClimateControl-0.5.beta50.jar) 
    	UCHIJAAAAAAAAAAAAAA	cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
    	UCHIJAAAAAAAAAAAAAA	cookingbook{1.0.134} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.134.jar) 
    	UCHIJAAAAAAAAAAAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.5.jar) 
    	UCHIJAAAAAAAAAAAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.5.jar) 
    	UCHIJAAAAAAAAAAAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.5.jar) 
    	UCHIJAAAAAAAAAAAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.5.jar) 
    	UCHIJAAAAAAAAAAAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.5.jar) 
    	UCHIJAAAAAAAAAAAAAA	excore{1.5.3} [EXCore] (Excore-1.5.3-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	creeperawareness{2.0.1} [Creeper Awareness] (CreeperAwareness-2.0.1-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	menagerie{1.0} [menagerie] (dark_menagerie-1.7.10-beta-3.1a.jar) 
    	UCHIJAAAAAAAAAAAAAA	DeadlyWorld{1.0.2} [Deadly World] (DeadlyWorld-1.7.10-1.0.2.jar) 
    	UCHIJAAAAAAAAAAAAAA	defaultworldgenerator{0.1-b13} [Default World Generator] (DefaultWorldGenerator-1.7.10-0.1-b13-universal.jar) 
    	UCHIJAAAAAAAAAAAAAA	dimdoors{2.2.5-test9} [Dimensional Doors] (DimensionalDoors-2.2.5-test9.jar) 
    	UCHIJAAAAAAAAAAAAAA	dldungeonsjdg{1.8.10} [Doomlike Dungeons] (DoomlikeDungeons-1.8.10-MC1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	dsurround{1.0.5.6} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.5.6.jar) 
    	UCHIJAAAAAAAAAAAAAA	endercore{1.7.10-0.2.0.31_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.31_beta.jar) 
    	UCHIJAAAAAAAAAAAAAA	enviromine{1.3.124} [EnviroMine] (EnviroMine-1.3.124.jar) 
    	UCHIJAAAAAAAAAAAAAA	farseek{1.0.11} [Farseek] (Farseek-1.0.11.jar) 
    	UCHIJAAAAAAAAAAAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    	UCHIJAAAAAAAAAAAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    	UCHIJAAAAAAAAAAAAAA	Steamcraft{0.29.2} [Flaxbeard's Steam Power] (FSP-1.7.10-0.29.2.jar) 
    	UCHIJAAAAAAAAAAAAAA	hammerz{0.1.7.37} [Hammerz] (Hammerz-1.7.10-0.1.7.37.jar) 
    	UCHIJAAAAAAAAAAAAAA	HardcoreDarkness{1.7} [Hardcore Darkness] (HardcoreDarkness-MC1.7.10-1.7.jar) 
    	UCHIJAAAAAAAAAAAAAA	HardcoreEnderExpansion{1.8.5} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.5.jar) 
    	UCHIJAAAAAAAAAAAAAA	IguanaTweaks{2B} [Iguana Tweaks] (IguanaTweaks-1.7.10-2B.jar) 
    	UCHIJAAAAAAAAAAAAAA	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
    	UCHIJAAAAAAAAAAAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
    	UCHIJAAAAAAAAAAAAAA	LiMI{1.0} [LiMI] (LiMI 1.0-1.jar) 
    	UCHIJAAAAAAAAAAAAAA	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
    	UCHIJAAAAAAAAAAAAAA	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAAAAAAAAAAAA	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAAAAAAAAAAAA	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAAAAAAAAAAAA	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAAAAAAAAAAAA	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAAAAAAAAAAAA	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAAAAAAAAAAAA	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAAAAAAAAAAAA	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAAAAAAAAAAAA	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAAAAAAAAAAAA	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAAAAAAAAAAAA	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAAAAAAAAAAAA	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAAAAAAAAAAAA	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    	UCHIJAAAAAAAAAAAAAA	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
    	UCHIJAAAAAAAAAAAAAA	ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.3-112.jar) 
    	UCHIJAAAAAAAAAAAAAA	TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.build991.jar) 
    	UCHIJAAAAAAAAAAAAAA	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
    	UCHIJAAAAAAAAAAAAAA	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar) 
    	UCHIJAAAAAAAAAAAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
    	UCHIJAAAAAAAAAAAAAA	MobProperties{1.0.2} [Mob Properties] (MobProperties-1.7.10-1.0.2.jar) 
    	UCHIJAAAAAAAAAAAAAA	modpackTweaks{MC1.7.10-1.2.0-26} [ModpackTweaks] (ModpackTweaks-MC1.7.10-1.2.0-26.jar) 
    	UCHIJAAAAAAAAAAAAAA	modtweaker2{0.9.5} [Mod Tweaker 2] (ModTweaker2-0.9.5.jar) 
    	UCHIJAAAAAAAAAAAAAA	NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) 
    	UCHIJAAAAAAAAAAAAAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
    	UCHIJAAAAAAAAAAAAAA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
    	UCHIJAAAAAAAAAAAAAA	nincraftlib{1.7.10-0.1.1+24} [Nincraft Lib] (NincraftLib-1.7.10-0.1.1+24.jar) 
    	UCHIJAAAAAAAAAAAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
    	UCHIJAAAAAAAAAAAAAA	temperateplants{1.7.2b} [Pam's Temperate Plants] (Pam's Temperate Plants.jar) 
    	UCHIJAAAAAAAAAAAAAA	PoorOres{1.7.10-1.4.8} [PoorOres] (PoorOres-1.7.10-1.4.8.jar) 
    	UCHIJAAAAAAAAAAAAAA	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
    	UCHIJAAAAAAAAAAAAAA	RPGAdvMod{1.0.0} [RPGAdvMod] (RPGAdvMod-1.0.0_1.7.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	RTG{1.7.10-0.8.0} [Realistic Terrain Generation] (RTG-1.7.10-0.8.0.jar) 
    	UCHIJAAAAAAAAAAAAAA	SaltMod{1.7.e} [Salty Mod] (SaltyMod-1.7.10-1.7.e.jar) 
    	UCHIJAAAAAAAAAAAAAA	SimpleAchievements{MC1.7.10-1.1.0-21} [Simple Achievements] (SimpleAchievements-MC1.7.10-1.1.0-21.jar) 
    	UCHIJAAAAAAAAAAAAAA	Somnia{-au} [Somnia] (Somnia-1.4.8.55.jar) 
    	UCHIJAAAAAAAAAAAAAA	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
    	UCHIJAAAAAAAAAAAAAA	SpecialAI{1.1.2} [Special AI] (SpecialAI-1.7.10-1.1.2.jar) 
    	UCHIJAAAAAAAAAAAAAA	SpecialMobs{3.2.2} [Special Mobs] (SpecialMobs-1.7.10-3.2.2.jar) 
    	UCHIJAAAAAAAAAAAAAA	SpiceOfLife{1.3.1} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.1.jar) 
    	UCHIJAAAAAAAAAAAAAA	Stackie{1.6.0.36} [Stackie] (Stackie-1.7.10-1.6.0.36-universal.jar) 
    	UCHIJAAAAAAAAAAAAAA	streams{0.2} [Streams] (Streams-0.2.jar) 
    	UCHIJAAAAAAAAAAAAAA	tnt_utilities{1.1.3} [TNTUtils] (tnt_utilities-mc1.7.10-1.1.3.jar) 
    	UCHIJAAAAAAAAAAAAAA	TML{4.0.1} [TooMuchLoot] (TooMuchLoot-1.7.10-4.0.1.B0.jar) 
    	UCHIJAAAAAAAAAAAAAA	TSteelworks{1.7.10-1.1.2} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.2-20.jar) 
    	UCHIJAAAAAAAAAAAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
    	UCHIJAAAAAAAAAAAAAA	twbbtweaks{1.7.10-1.0.0+32} [TWBB Tweaks] (TWBBTweaks-1.7.10-1.0.0+32.jar) 
    	UCHIJAAAAAAAAAAAAAA	weather2{v2.3.11} [Localized Weather & Storms] (weather2-1.7.10-2.3.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	yampst{1.3.5} [YAMPST] (Yampst-There Will Be Blood-1.0.0-FTB-Curse.jar) 
    	UCHIJAAAAAAAAAAAAAA	YeOldeTanks{1.2.0} [Ye Olde Tanks] (YeOldeTanks-1.7.10-1.4.5.jar) 
    	UCHIJAAAAAAAAAAAAAA	ZAMod{v1.10} [Zombie Awareness] (zombieawareness-1.7.10-1.10.jar) 
    	UCHIJAAAAAAAAAAAAAA	aobd{2.9.1} [Another One Bites The Dust] (AOBD-2.9.1.jar) 
    	UCHIJAAAAAAAAAAAAAA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
    	UCHIJAAAAAAAAAAAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    	UCHIJAAAAAAAAAAAAAA	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
    	UCHIJAAAAAAAAAAAAAA	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
    	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    	CoFHCore: -[1.7.10]3.1.2-325
    	Mantle Environment: Environment healthy.
    	ThermalFoundation: -[1.7.10]1.2.3-112
    	TConstruct Environment: Environment healthy.
    	NetherOres: -[1.7.10]2.3.1-22
    	Profiler Position: N/A (disabled)
    	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    	Player Count: 1 / 8; [EntityPlayerMP['Dragzorath'/418669, l='New World', x=334.50, y=74.00, z=1063.50]]
    	Type: Integrated Server (map_client.txt)
    	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by UndeadZeratul** [comment]
It looks like no further changes are going to be made against this, and since it's a rare crash that shouldn't cause permanent damage, I'm going to mark this as won't fix and close it.
